#!/bin/bash
#
# Regenerates Scripture_Unlock/Resources/Secrets.xcconfig from Bitwarden.
#
# The point is that the file no longer needs to be kept anywhere: it is derived
# on demand, so a lost or wiped machine needs only a Bitwarden login rather than a
# copy of the plaintext keys.
#
# Usage:
#   export BW_SESSION=$(bw unlock --raw)
#   ./scripts/gen-secrets.sh
#
# Add to a build phase if you want it automatic — but note it will prompt for a
# session if BW_SESSION is unset, so keep it out of CI unless the session is
# injected there.
#
set -euo pipefail

ITEM_NAME="Scripture Unlock — build secrets"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
XCCONFIG="$ROOT/Scripture_Unlock/Resources/Secrets.xcconfig"

if [[ -z "${BW_SESSION:-}" ]]; then
  echo "error: BW_SESSION is not set. Run: export BW_SESSION=\$(bw unlock --raw)" >&2
  exit 1
fi

echo "Fetching \"$ITEM_NAME\" from Bitwarden…"
ITEM_JSON=$(bw get item "$ITEM_NAME" --session "$BW_SESSION")

# Write via a temp file so a failure never leaves a half-written config that
# would build into a broken app.
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

printf '%s' "$ITEM_JSON" | python3 - "$TMP" <<'PY'
import json, sys

tmp = sys.argv[1]
item = json.load(sys.stdin)
fields = {f["name"]: f.get("value") or "" for f in item.get("fields") or []}

required = ["SUPABASE_HOST", "SUPABASE_ANON_KEY", "GEMINI_API_KEY"]
missing = [k for k in required if not fields.get(k)]
if missing:
    sys.exit(f"error: vault item is missing: {', '.join(missing)}")

for k, v in fields.items():
    if "//" in v:
        sys.exit(f"error: {k} contains '//', which xcconfig treats as a comment. "
                 "Store bare hosts, not URLs.")

with open(tmp, "w") as f:
    f.write("// GENERATED by scripts/gen-secrets.sh — do not edit, do not commit.\n")
    f.write("// Source of truth is the Bitwarden item \"Scripture Unlock — build secrets\".\n")
    f.write("// Only these three keys reach the app; Scripture-Unlock-Info.plist maps them.\n\n")
    for k in required:
        f.write(f"{k} = {fields[k]}\n")

print(f"wrote {len(required)} keys")
PY

mkdir -p "$(dirname "$XCCONFIG")"
mv "$TMP" "$XCCONFIG"
chmod 600 "$XCCONFIG"
trap - EXIT
echo "Regenerated $XCCONFIG (mode 600)"
