#!/usr/bin/env python3
"""Render Secrets.xcconfig from a Bitwarden item JSON dump.

Kept as a separate file rather than a heredoc inside gen-secrets.sh: the heredoc
form owns stdin, which collided with reading the item JSON from a pipe.

Usage: render_xcconfig.py <item.json> <output.xcconfig>
"""

import json
import sys

# Only these reach the app. Scripture-Unlock-Info.plist maps exactly these three
# into the bundle, and the services read them via
# Bundle.main.object(forInfoDictionaryKey:). Anything else is inert at runtime.
REQUIRED = ["SUPABASE_HOST", "SUPABASE_ANON_KEY", "GEMINI_API_KEY"]


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <item.json> <output.xcconfig>", file=sys.stderr)
        return 2

    item_path, out_path = sys.argv[1], sys.argv[2]

    try:
        with open(item_path) as f:
            item = json.load(f)
    except json.JSONDecodeError as exc:
        print(f"error: could not parse Bitwarden output as JSON: {exc}", file=sys.stderr)
        print("       (is the session valid? try: bw sync)", file=sys.stderr)
        return 1

    fields = {f["name"]: (f.get("value") or "") for f in (item.get("fields") or [])}

    missing = [k for k in REQUIRED if not fields.get(k)]
    if missing:
        print(f"error: vault item is missing or has empty: {', '.join(missing)}", file=sys.stderr)
        return 1

    # xcconfig treats "//" as the start of a comment, so a value like
    # "https://project.supabase.co" silently truncates to "https:" and the app
    # fails at runtime with no build error. Refuse rather than emit that.
    for key in REQUIRED:
        if "//" in fields[key]:
            print(
                f"error: {key} contains '//', which xcconfig reads as a comment. "
                "Store a bare host, not a URL.",
                file=sys.stderr,
            )
            return 1

    with open(out_path, "w") as f:
        f.write("// GENERATED by scripts/gen-secrets.sh — do not edit, do not commit.\n")
        f.write('// Source of truth: Bitwarden item "Scripture Unlock — build secrets".\n')
        f.write("// Only these three keys reach the app; Scripture-Unlock-Info.plist maps them.\n\n")
        for key in REQUIRED:
            f.write(f"{key} = {fields[key]}\n")

    print(f"rendered {len(REQUIRED)} keys")
    return 0


if __name__ == "__main__":
    sys.exit(main())
